#!/bin/sh

# Async IT Sàrl - 2025 - Jonas Sauge

# This script is used to show some usefull informations when loging in on a system

# V1.0: Initial Release
# V1.1: Added uptime
# V1.2: Use hostname -I insead of -i to show all host IP'shttps://github.com/async-it/debian/blob/main/motd/01-async
# V1.3: Get public ip's
# V1.4: Add date
# V1.5: Add Cpu cores total

freespace=$(df -H --type mount --type btrfs --type ext4 --type ext3 --type ext2 --type vfat --type iso9660)
kernelversion=$(uname -r)
uptime=$(uptime -p)
systemdate=$(date +"%d.%m.%Y %H:%M:%S")
cpucores=$(nproc --all)

echo "
Welcome to:  	  $(hostname)
User:       	  $(id -u -n)
Contact:          Async IT Sàrl

Operating System: $(awk -F= '/PRETTY/ {gsub(/"/,"");print $2}' /etc/os-release)
Kernel version:   $kernelversion
Uptime:           $uptime
System time:      $systemdate

Host local IP:    $(hostname -I)
Public IPv4       $(curl --connect-timeout 1 myipv4.addr.tools)
Public IPv6       $(curl --connect-timeout 1 myipv6.addr.tools)

CPU:              $cpucores cores -$(cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d':' -f2)
Memory:           $(free -m | head -n 2 | tail -n 1 | awk {'print $2'}) M
Swap:      	  $(free -m | tail -n 1 | awk {'print $2'}) M

Disk:      
 $(echo "$freespace")
 
 "
